### ISSUE TITLE
Multi Monitor Support

### ISSUE THREAD

**Issue by quagsirus** [ChrisAnd1998/FalconX#1]
The software doesn't center the taskbar on the non-primary monitor

**Comment by convalise** [comment]
I second this. Loving the tool by the way. :)

**Comment by rknx** [comment]
+1

**Comment by keeganatorr** [comment]
+1 to this, older versions of the program supported this

**Comment by hectorviov** [comment]
I'd love to see this too.

**Comment by sharma** [comment]
Another vote for this!

**Comment by mjuksel** [comment]
We can apply a custom offset. Rightclick tray icon > position > amount.
I use 1798 on 1920*1080 + 1680*1050. I'm assuming 2x 1080P would be 1920.

**Comment by Saijin-Naib** [comment]
Confirming the same behavior with the W10 Store version. Otherwise, neat application.

**Comment by ChrisAnd1998** [comment]
I hope to add it later when FalconX is completely stable. It's very easy to add when all your screen have the same sizes, DPI and settings because, then I can just passthrough the same calculations for all taskbars.

**Comment by rknx** [comment]
@ChrisAnd1998, I was just wondering if you are going to work on this issue for FalconX3?

**Comment by ChrisAnd1998** [comment]
@rknx I can't promise you anything but, i can only say that i want to.
And FalconX still needs to be completely stable first.

**Comment by BigMangos** [comment]
Wishing your work ,Thanks

**Comment by diogotcorreia** [comment]
+1

**Comment by ChrisAnd1998** [comment]
Its comming...

**Comment by rknx** [comment]
Nice. I'm willing to test it if you need that.

**Comment by ChrisAnd1998** [comment]
Here, i am gonna test it right now on some other pc's
https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by rknx** [comment]
@ChrisAnd1998 Seems to be password protected. Can you email me the pass? rknx@outlook.com

**Comment by ChrisAnd1998** [comment]
CA

**Comment by ChrisAnd1998** [comment]
1.2.2.0 Released
