### ISSUE TITLE
FalconX doesn't work for 1.3.0 and 1.4.0 on Windows 1809

### ISSUE THREAD

**Issue by user00101010** [ChrisAnd1998/FalconX#10]
Hello Chris,

And thank you for your work in FalconX! It's an awesome handy utility I combine with TranslucentTB to get a nice modern look and a dock utility all in one. I absolutely love it, as I find the classic windows taskbar position quite outdated.

On to the topic, I'm running Windows 1809 17763.615 (latest for my system). FalconX doesn't work with the latest 1.3.0 and 1.4.0 versions. I downloaded 1.2.0 from the archive, and can confirm this is running successfully! 

I was using the UWP app before, on version 1.2.0 I believe (the UI is looking a bit different, but I think this is due to UWP/desktop differences?) as I never had any of the new options available.

Furthermore, I noticed that using 1.2.0 desktop app is blazing fast, unlike the UWP app which took a good few seconds to load (which flashing and etc.).

**Comment by ChrisAnd1998** [comment]
Does it work now? with the 01.08.2019 update.

**Comment by user00101010** [comment]
Thank you for the update. I do confirm that everything seems to be working great now with the desktop version!

The only exception I noticed is the new centering feature, it seems to offset the centering by a large margin, where as it shouldn't move it at all with no toolbars, or barely move it with my 1-icon wide toolbar. Instead even when there are no toolbars present, it's way off center with the option enabled. I can open a separate issue for this if you prefer.

Thank you again.

**Comment by ChrisAnd1998** [comment]
Nice to hear that! I didn't know a short good name for that new feature but, it should center between your start menu icon, search and taskview earia and you notification earia with the clock, volume etc... If you look closely you can see you have the same space on the left and right between those earia's when you enable it.
