### ISSUE TITLE
Feature Request: Spacers/Per-Icon-offset

### ISSUE THREAD

**Issue by matthewcorreia** [ChrisAnd1998/FalconX#12]
I'm not sure if it's possible or difficult, but I thought it would be nice to be able to set an offset per icon/icon-position, or somehow add spacing between specific icons, in order to create implied grouping.

This functionality exists within the Mac OS Dock by using a 'spacer' dock item, for example.

**Comment by ChrisAnd1998** [comment]
Sadly it's not possible. I have tried many ways to move them individually but, it just won't. The taskbar is some kind of a toolbar control so thats probably the reason why it's not possible.

If i somehow magically manage to do it anyway i will definitly add it to FalconX ;)

**Comment by v-rogg** [comment]
For a quite dirty way this might be an option for you
https://www.groovypost.com/howto/howto/add-a-blank-space-to-the-windows-7-taskbar/
