### ISSUE TITLE
Symantec Endpoint Protection Virus Alert

### ISSUE THREAD

**Issue by pan-theis** [ChrisAnd1998/FalconX#13]
The current version FalconX_14.07.2019_1.1.4.0 is blacklisted with **WS.Reputation.1** in Symantec Endpoint Protection Virus Alert. 

https://www.symantec.com/security-center/writeup/2010-051308-1854-99

**Comment by ChrisAnd1998** [comment]
Thanks for letting me know. I will contact them right away.

**Comment by ChrisAnd1998** [comment]
Hi,

I got their response.

We have been unable to reproduce the detection issue described in your submission. Our investigation shows that the software you submitted is known-good and as such does not trigger any detections. A possible reason for this could be that the status of your software changed automatically between the time of your submission and now.

**Comment by pan-theis** [comment]
Hi Chris,

I took the liberty and already reported the false positive. 

> In relation to submission 161655.
> 
> Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:
> 
>     File name: FalconX.exe
>     MD5: C20A10E742EC72940B0C3386AF0DF757
>     SHA256: 86743622EB51F7C688670F6DBE9217D2DE8006C83DE36FDEBA85FEABB342A414
>     Note: Whitelisting may take up to 24 hours to take effect via Live Update

**Comment by ChrisAnd1998** [comment]
Ah, thank you :)

That probably explains why it was already marked as good.
