### ISSUE TITLE
Version 14.07.2019 does not start in Windows 10 19.03

### ISSUE THREAD

**Issue by Rosmaninho** [ChrisAnd1998/FalconX#14]
After downloading the version 14.07.2019, I deleted the 11.07.2019 version.
I clicked on the 14.07.2019 version and it did not start. No icon in tray, and no relocation of the taskbar. It's impossible to make it work.

I had to download again the 11.07.2019 version and have remained on that one.

Windows 10, 19.03 update version.

**Comment by ChrisAnd1998** [comment]
Does it work now? with the 01.08.2019 update.

**Comment by Rosmaninho** [comment]
It works!! :D
________________________________

**Comment by Rosmaninho** [comment]
You really did an amazing work. Can I suggest you another potential app?

I like Falcon X because it makes the Taskbar look like a dock. However, one big issue in Windows now, if one wants a desktop without icons, is the Recycling Bin.
To add a shortcut to the taskbar of the recycling bin that keeps the right-click menu actions one has to:
1 - create an empty folder and add a new toolbar to the taskbar of that folder,
2 - add a shortcut to the recycling bin in the folder of that toolbar.

However this raises a couple of issues. Falcon X does not shift the position of this "recycling bin" icon in the taskbar.
I wanted to suggest you to create an app that places a Recycling Bin icon in the taskbar (with access to the right-click options of the desktop icon) that can be centered by FalconX.

Also another suggestion: Your work is amazing, you should set up some way for people to pay you for it. I don't know, make like the Paint.net developer and make the Windows Store version paid, include a paypal donation in your website, set up a Patreon account...

Thanks for the amazing support to a product that is free. 🙂

All the best

________________________________

**Comment by ChrisAnd1998** [comment]
Thanks! intresting idea, i will add it as an option in FalconX if i manage to get that working.

**Comment by demonawakens** [comment]
After clicking oon falconx it works nice but when i have changed large icon to small icon settings in taskbar setting, then it revert back as usual. after that i have again install falconx but not working. pls help me out.

Screenshot also attached for reference.

![image](https://user-images.githubusercontent.com/63064381/78273571-a24a2380-752c-11ea-9b66-862f50a88e18.png)
