### ISSUE TITLE
Play/pause button stops working when FalconX is running

### ISSUE THREAD

**Issue by GibStorm** [ChrisAnd1998/FalconX#16]
My Logitech G810 keyboard has media keys. Whenever I run FalconX, the Play/Pause button stops working. As soon as I quit FalconX, it starts working again.

I don't know if it's caused by a conflict with Logitechs G Hub software, but it prevents me from using FalconX.

**Comment by user00101010** [comment]
Not the developer, but can confirm that on my system this bug doesn't occur for the media keys on my keyboard. Could you please try turning off the Logitech G Hub software, testing and posting the results to see if it's related to the Logitech software.
