### ISSUE TITLE
FalconX not launching from windows store

### ISSUE THREAD

**Issue by MMRREE** [ChrisAnd1998/FalconX#17]
In FalconX version 1.1.5.0 from the microsoft store there is an option to launch on startup, but even when selected, when I restart my computer the app does not launch. I am on windows version 1903. Is it a local problem, or is it an ongoing issue to resolve.

**Comment by gregorskii** [comment]
Where is the launch on startup option? I do not see it.

**Comment by ChrisAnd1998** [comment]
Should be fixed now.
