### ISSUE TITLE
Overflow issue makes the icons hard to see

### ISSUE THREAD

**Issue by hohoaisan** [ChrisAnd1998/FalconX#2]
![image](https://user-images.githubusercontent.com/26185060/60711211-8f270a80-9f3e-11e9-9e2e-4169f4dca4ef.png)

**Comment by user00101010** [comment]
@ChrisAnd1998 Thank you very much for adding this! I have a 1440p 27-inch display (100% scaling) with only 7 icons pinned on my taskbar, however I have also ran into the issue when I have had many apps opened. It's great news that this has been fixed! I will update if I run into any issues again
