### ISSUE TITLE
Causes "Explorer.exe" to crash

### ISSUE THREAD

**Issue by johneusebio** [ChrisAnd1998/FalconX#21]
I'm running FalconX on my Surface Book 2, and I *think* it occasionally causes my Windows taskbar to crash. The taskbar becomes unresponsive, eventually prompts me to End Process (stating Microsoft Windows has crashed), and then it appears that my entire Windows shell ends. Sometimes the Windows shell restarts after a few minutes, but other times I need to force my computer to shut down.

I'm using the Windows Store version, and my windows version OS Build 18362.356.

I'm leaving it disabled for now until a fix is issued. If the same error happens again without FalconX running, then I'll post an update to this thread promptly.

**Comment by ChrisAnd1998** [comment]
Thanks for letting me know :)
No one reported this issue before though. 
It could be possible that a third-party startmenu has a conflict with FalconX causing the Explorer to crash.

**Comment by johneusebio** [comment]
6 days on and no crash.

I don't think a third-party start menu app is the issue. I'm using QuickLook (windows store version) and ear trumpet. And I'm using the same apps on my desktop at home, which has *never* crashed when used in conjunction with FalconX. 

One potential cause I thought of is the graphics card disconnecting. Since the graphics card on the surface book is detachable, it has to include software to shut it off. And lately, I've been having issues where my graphics card won't register, even with the base attached. Maybe a spontaneous graphics card failure could be causing this?

I'll test this out by forcing FalconX to only use Intel integrated graphics.

**Comment by ChrisAnd1998** [comment]
Thanks for the update. 
Would be weird if that fixes the issue though.
I'll be waiting for the next update...

**Comment by johneusebio** [comment]
![image](https://user-images.githubusercontent.com/10139189/65185008-b0bf6a80-da34-11e9-9468-5d0228af3c8a.png)

Happened again when running exclusively using the Intel GPU, so the cause isn't the dedicated GPU spontaneously disconnecting.

CPU usage and power consumption spike way up when this happens, apparently.

**Comment by ChrisAnd1998** [comment]
I am currently working on 1.1.9.0 and i totally replaced the animation library.

It's still a testing build but, it may fix your issue.

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by johneusebio** [comment]
This issue is happening again. And with pretty high regularity.
