### ISSUE TITLE
Program keeps closing itselft

### ISSUE THREAD

**Issue by convalise** [ChrisAnd1998/FalconX#24]
Hello.
I configured FalconX to run at startup, and it works fine, but sometimes when I start my computer it closes for no apparent reason. After that, when I try to start it manually, it is always a battle because I have to open it like ten times until it sticks and stays running. Windows 10 1903, OS Build 18362.356.
Keep up the good work! :)

**Comment by ChrisAnd1998** [comment]
Thanks for letting me know :)

Do you have any third-party startmenu or tweakers like 7+taskbartweaker?
There could be a conflict between FalconX and another application.

**Comment by convalise** [comment]
Hello.
The only third-party I use is indeed 7+TW, maybe it's the reason FalconX closes the first time, but the "have to open ten times" thing happens even after killing 7+TW, so I'm not sure it's related.
For the process to be terminated like that, maybe it's just an exception that you are not catching on the app start, I don't know, sorry for being nosy. 😁

**Comment by ChrisAnd1998** [comment]
I found out that the current animation library caused most issues. So i am currently working on update 1.1.9.0 and swapped it out with another one. Here is a testing buid

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

This could fix it.

**Comment by convalise** [comment]
I haven't had the issue since the update.

**Comment by ChrisAnd1998** [comment]
Finally! Hope it stays that way.
