### ISSUE TITLE
Started getting this error from last week.

### ISSUE THREAD

**Issue by Rohitms** [ChrisAnd1998/FalconX#26]
![image](https://user-images.githubusercontent.com/15374182/66711473-5f439a80-edaa-11e9-826f-286b7a7ec760.png)

**Comment by ChrisAnd1998** [comment]
This is the store version right?
I am on it, some people have reported it to

**Comment by ChrisAnd1998** [comment]
Can you delete the folder? **C:\Users\rohit\AppData\Local\Chris_Andriessen**
And then run FalconX.

**Comment by Rohitms** [comment]
I don't have a folder named "Chris_Andriessen" in C:\Users\rohit\AppData\Local\

**Comment by ChrisAnd1998** [comment]
If you have run the new version from my website then it's completely removed by FalconX because, it now uses it's own config to avoid this error. 

I have put the newest version 1.2.5.0 in submission to the store yesterday so it could arrive any moment.

**Comment by ChrisAnd1998** [comment]
1.2.5.0 should be in the store now.

**Comment by Rohitms** [comment]
Updated and now it's working fine. Good that you added Transparent TB option, now I can let go of TranslucentTB.

Very thank you for the quick fix and for the updates.

**Comment by ChrisAnd1998** [comment]
I am happy it works now :)

The transparant taskbar option is an experimental feature so it could get some optimizations next update.
