### ISSUE TITLE
When a new application is opened, the apps, sometimes, don't centre themselves

### ISSUE THREAD

**Issue by rahul16899** [ChrisAnd1998/FalconX#29]
When a new application is opened, the apps at the bottom, sometimes, don't move themselves to be at the center. If I restart the program, it works and after sometime, the issue comes again. I have included a screenshot which clearly shows that the apps just appears on the right side without the other apps moving themselves to be at the center. Please fix it.

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/21038198/66831317-fd835c00-ef74-11e9-87e8-cb5b78e89897.PNG">

**Comment by ChrisAnd1998** [comment]
Does this happen with the multi monitor option enabled or disabled?

**Comment by rahul16899** [comment]
> Does this happen with the multi monitor option enabled or disabled?

Disabled

**Comment by ChrisAnd1998** [comment]
I am currentlly working on the next update.
Does it still happen with _FalconX_TESTING_1.2.6.0_v2.zip_

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by rahul16899** [comment]
Update: I did a reset and, guess what, it works perfectly now.

**Comment by ChrisAnd1998** [comment]
Awesome! version 1.2.5.0 or 1.2.6.0 ?

**Comment by rahul16899** [comment]
version 1.2.5.0

**Comment by ChrisAnd1998** [comment]
Allright thanks 😁, It gets checked in 1.2.6.0 if it's at the right position. And forces a move when it isn't.
