### ISSUE TITLE
Startup Problem (Microsoft Store Version)

### ISSUE THREAD

**Issue by jerryshaw12** [ChrisAnd1998/FalconX#3]
the app does not launch at startup even i enable the startup
![image](https://user-images.githubusercontent.com/16917061/60711861-fb563e00-9f3f-11e9-8ac7-9ee80090959d.png)

![image](https://user-images.githubusercontent.com/16917061/60711886-06a96980-9f40-11e9-8b34-555341404d0f.png)

**Comment by ChrisAnd1998** [comment]
Yes, It doesn't show in task manager but, does it run at startup after the latest update?

**Comment by user00101010** [comment]
I had the same issue @ChrisAnd1998 and I was using the UWP version as well. The app was not showing up in the task manager, nor actually booting at start-up. I cannot confirm if this is fixed on the new versions as they do not work for me as I reported in issue #10 .

I can confirm that the desktop version 1.2.0 of the app auto start-up works great, and it does appear in the task manager as expected.

**Comment by ChrisAnd1998** [comment]
@jerryshaw12 Do you still have this issue? with 1.1.4.0

**Comment by ChrisAnd1998** [comment]
Fixed ;)
