### ISSUE TITLE
Feature Request: Only center non-pinned items

### ISSUE THREAD

**Issue by Saijin-Naib** [ChrisAnd1998/FalconX#4]
I don't know if this is even possible, but I think it'd be more visually consistent if only non-pinned icons were centered (as an option). This would leave the pins aligned with the system icons (search/cortana/task view), and leave running applications centered/separated visually, which I like the idea of.

Thanks for the tool! Didn't even know I wanted something like this.

**Comment by ChrisAnd1998** [comment]
I have tried to move them individually but i can't get them to move anywhere. They just stick together, i don't think it's possible :(
