### ISSUE TITLE
[Bug] Second click on icon does not minimize windows

### ISSUE THREAD

**Issue by allanveloso** [ChrisAnd1998/FalconX#7]
After last update on Windows Store, a second click on the icon does not minimize the window.

**Comment by Xs3roN** [comment]
I had this issue even on version from 23 of June.

**Comment by adyanth** [comment]
Both the windows store and the zip version does not minimize the window on click.

**Comment by ChrisAnd1998** [comment]
That should be fixed now.

**Comment by adyanth** [comment]
Works perfectly. Even a new window for the settings I see!
Any ETA for the change in Store?

**Comment by ChrisAnd1998** [comment]
Glad to hear that! Uploaded it to the Store 1 hour ago. It will take 3 business days for MS to add it. Sometimes 1 or 2 days.
