### ISSUE TITLE
New update keeps a window open for it to be running

### ISSUE THREAD

**Issue by adyanth** [ChrisAnd1998/FalconX#8]
The new update keeps a window open when it is running. So alt+tabbing also selects that window. Closing the window also closes the application.
Standard behaviour for an app running in the tray would be not to show up in the open windows, correct?

![Screenshot_2](https://user-images.githubusercontent.com/33192449/61172579-caab7f80-a5a3-11e9-8629-de30f7a60938.png)

**Comment by ChrisAnd1998** [comment]
Hmm, what build of Windows 10 are you using? this doesn't happen on my 1903 build tho.
Sorry for the late reply.

**Comment by adyanth** [comment]
Windows build 1903.
It was in the 13.07.2019 build of falcon X
Fixed in 14.07.2019

Thanks
