### ISSUE TITLE
buttons cut off on my system

### ISSUE THREAD

**Issue by deluxghost** [ChrisAnd1998/FalconX#9]
![chrome_2019-07-18_21-56-13](https://user-images.githubusercontent.com/5835759/61463702-8f47f100-a9a7-11e9-92fa-4464d381e546.png)

Windows 1903 / FalconX latest

for some locales such as Chinese/Japanese, the default font of windows is slightly different from English locale, thus the size of elements are different too, as an result, the necessary buttons cut off.

after force resizing the form with a tool, i can see them, but thats is not a solution, please change the layout, dont rely on pixels calculating

**Comment by xiaovie** [comment]
I also encountered this problem, please ask the author to fix the bug as soon as possible.

**Comment by Dvaderfun** [comment]
Butons cut off on Windows 10, but in windows 8 compatbility mode you can partially see them

![image](https://user-images.githubusercontent.com/17787753/61723619-1c5ac380-ad75-11e9-89c8-414a32400610.png)

**Comment by ChrisAnd1998** [comment]
I have made the form sizable in the latest update. So you can resize it until you see the buttons. I don't know whats causing this yet.

**Comment by deluxghost** [comment]
looks like the controls have fixed size and location in pixel unit, e.g.

https://github.com/ChrisAnd1998/FalconX/blob/master/FalconX3/Form1.Designer.vb#L69-L71

im not sure if this causes the issue, but we'd better use some flexible layout controls such as grid

**Comment by ChrisAnd1998** [comment]
Yeah, your'e right but, it shouldn't happen with everything fixed.
A grid may fix this.

**Comment by deluxghost** [comment]
1.1.5.0 fixed for me
